# Generated by Django 6.1.1 on 2026-09-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
