# Generated by Django 6.1.1 on 2026-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_rename_create_at_customer_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
