# Generated by Django 6.0.8 on 2026-10-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PIPELINE_CREATE', 'Pipeline Created'), ('PIPELINE_UPDATE', 'Pipeline Updated'), ('PIPELINE_DELETE', 'Pipeline Deleted'), ('PIPELINE_RUN', 'Pipeline Run Triggered'), ('SCHEDULE_UPDATE', 'Schedule Updated'), ('SCHEDULE_TOGGLE', 'Schedule Toggled (Pause/Resume)'), ('SCHEDULE_DELETE', 'Schedule Deleted')], max_length=50)),
                ('resource', models.CharField(help_text='The target entity (e.g. Pipeline #31)', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Additional details or metadata', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system/automated events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
