# Generated by Django 6.1.1 on 2026-10-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0005_delete_customer_pipeline_source_pipeline_table_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=20)),
                ('records_extracted', models.IntegerField(default=0)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_loaded', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(help_text='The pipeline that was executed.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipeline')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who started this execution (null if scheduled/system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
